services:
  backend:
    build: ./backend
    volumes:
      - ./flickr8k/data:/data/flickr8k:ro
      - db-data:/data/db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db-data:
